#!/bin/sh
#
# =================================================
# contactSheet (version 0.0)
# by Carlos Vigil Vásquez
#
# Make contact sheet of images of working directory
#
# https://github.com/cvigilv/
# =================================================

# SCRIPT HISTORY
_version_="0.0"
_released_="Currently in development"
_title_="contactSheet - Easy proofing of images! $_version_"

magick montage -label "%f" -title "$(basename $PWD)" -tile 6x7 -fill 'black' -pointsize 36 -background "#f1f1f1ff" -bordercolor "#5f5f5fff" -borderwidth 2 -geometry 600x400+20+20 *.tif* $(basename $PWD)C.jpg
