#!/bin/sh
#
# =============================================
# dmenu_shortcuts (version 0.0)
# by Carlos Vigil Vásquez
#
# Navigate files in a faster fashion
#
# https://github.com/cvigilv/
# =============================================


OPTIONS="Github\nUniversity\nCurrent semester"

CHOSEN=$(echo -e "$OPTIONS" | dmenu -i -p "Where do you wanna go?")

case "$CHOSEN" in
    "Github") $TERMINAL -e ranger $HOME/Repos/;;
    "University") $TERMINAL -e ranger $DRIVE/Universidad/;;
    "Current semester") $TERMINAL -e ranger $DRIVE/Universidad/9no\ Semestre/;;
esac
