#!/usr/bin/env bash
# name: doi2bibtex
#  ver: v0.0
# date: 2024/04/03
# desc: Get bibtex object from DOI.
# auth: Carlos Vigil-Vásquez
# deps: curl
#  lic: Permission to copy and modify is granted under the MIT license
#   cc: Copyright (C) 2024 Carlos Vigil-Vásquez (carlos.vigil.v@gmail.com)

set -eo pipefail
if [[ "${TRACE-0}" == "1" ]]; then
	set -o xtrace
fi

# Helper functions
function usage() {
	echo "Usage: doi2bibtex <doi>"
}

function help_message() {
	echo "
Get bibtex object from DOI.
"
}

function main() {
	cd "$(dirname "$0")"
	>&2 echo "doi2bibtex - v0.0"

	if [ $# -ne 1 ]; then
		usage
		exit
	elif [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
		usage
		help_message
		exit
	fi

	(doi2citation "${1}" "bibtex" 2>/dev/null)
}

main "$@"
