#!/bin/sh
#
# =============================================
# i3block_todo (version 0.0)
# by Carlos Vigil Vásquez
#
# Get ToDo statistics for i3blocks
#
# https://github.com/cvigilv/
# =============================================

# Get amount of undone and partly done tasks
UNDONE=$(cat $TODO | grep '\[\]' | wc -l)
PARTLY=$(cat $TODO | grep '\[·\]' | wc -l)
DONE=$(cat $TODO | grep '\[x\]' | wc -l)

echo "  $UNDONE  $PARTLY  $DONE "

case $BLOCK_BUTTON in
    1) $TERMINAL -e vim $TODO;;
esac

exit 0
