#!/bin/sh
#
# =============================================
# i3block_usage (version 0.0)
# by Carlos Vigil Vásquez
#
# Get CPU and memory info for i3blocks
#
# https://github.com/cvigilv/
# =============================================

# Get CPU & memory usage
CPU=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}')
MEM=$(free -m | grep 'Mem:' | awk '{usage=$3*100/$2} END {print usage "%"}')

echo "  $CPU   $MEM "

case $BLOCK_BUTTON in
    1) $TERMINAL -e htop;;
    3) $TERMINAL -e gtop;;
esac

exit 0
