#!/bin/sh

# = IGpost =====================================================================
#
# Version 0.1 (2019.10.18)
# Create standarized posts for Instagram
#
# by Carlos Vigil Vásquez
# https://github.com/cvigilv/
# ==============================================================================

# SCRIPT HISTORY
_version_="0.1"
_released_="Currently in development"
_title_="IGpost - Standarized Instagram posts $_version_"

# ARGUMENT PARSING
 helper()
{
echo
"
Usage: IGpost [arguments]

Arguments:
    -h or --help        Print Help (this message) and exit
    --version           Print version information and exit";
exit 1;
}

ver()
{
echo
"
Version:        $_version_
Release:        $_released_";
exit 1;
}

echo "$_title_"

# Check if image is B&W or Colour
c=$(convert $1 -colorspace HSL -channel g -separate +channel -format "%[fx:mean]" info:)

if [ "$c" == "0" ]; then
    # B&W image
    convert -size 2000x2000 xc:white /tmp/white_canvas.png
    convert $1 -resize 1850x1850\> -bordercolor black -border 10 /tmp/resized_$(basename $1)
    composite -gravity center /tmp/resized_$(basename $1) /tmp/white_canvas.png $(echo $1 | sed --expression='s/.jpg/-IG.jpg/g')
    exit
else
    # Colour image
    avg_c=$(convert $1 -scale 50x50! -depth 8 +dither -colors 8 -format "%c" histogram:info: |sed -n 's/^[ ]*\(.*\):.*[#]\([0-9a-fA-F]*\) .*$/\1 #\2/p' | sort -r -n -k 1 -t " " | head -n5 | shuf -n 1 | awk '{print $NF}')
    convert -size 2000x2000 xc:${avg_c} /tmp/coloured_canvas.png
    convert $1 -resize 1850x1850\> -bordercolor white -border 20 /tmp/resized_$(basename $1)
    composite -gravity center /tmp/resized_$(basename $1) /tmp/coloured_canvas.png -type TrueColor $(echo $1 | sed --expression='s/.jpg/-IG.jpg/g')
    exit
fi
exit
