#!/bin/sh
#
# =============================================
# Looper (version 0.0)
# by Carlos Vigil Vásquez
#
# Loop through stuff to do other stuff
#
# https://github.com/cvigilv/
# =============================================

# SCRIPT HISTORY
_version_="0.0"
_released_="Currently in development"
_title_="Looper - Loop the loop! $_version_"

CWD=$(pwd)

echo -e "${_title_}\n$(date +%F\ %H:%M:%S)"
echo -e "\nRunning $1 in $CWD"
for DIR in *; do
    if [ -d "$DIR" ]; then
        cd $DIR
        echo "- $1 $DIR"
        $1
        cd $CWD
    else
        $1 $DIR
    fi
done

echo -e "\nDone! Time elapsed: $(date -d@$SECONDS -u +%H:%M:%S)"
