#!/bin/sh
#
# =============================================
# setBG.sh (version 0.0)
# by Carlos Vigil Vásquez
#
# Small script for setting my background image
#
# https://github.com/cvigilv/
# =============================================

# SCRIPT HISTORY
_version_="0.0"
_released_="Currently in development"
_title_="setBG - Set my background boy! $_version_"

feh --bg-fill --randomize $HOME/.wallpapers/* && \
    notify-send "setBG" "Changed wallpaper!"
