#!/bin/sh

_version_="0.0"
_title_="tmux_lab - $_version_"

tmux has-session -t Lab
if [[ $? != 0 ]]; then
	cd ~/uni/lab/
	# Detach of current tmux session if in one
	# "tmux inception is the worst kind of inception"
	if [[ -n $TMUX ]]; then 
		tmux detach
	fi
	
	# Create a new session with some windows opened
	tmux new-session -s Lab -n Journal -d
	tmux send-keys 'vim ~/repo/cuadernos/LabJournal.md'
	
	tmux new-window -n Git -t Lab
	tmux split-window -h -t Lab:1
	tmux select-window -t Lab:1.2
	tmux send-keys 'cd ~/uni/lab/schuellerlab/cvigilv/SCRIPTS' 'C-m'
	tmux send-keys 'git status' 'C-m'
	
	tmux select-window -t Lab:0

fi
tmux -2 attach -t Lab
