#!/bin/sh

# = dmenu_<++> =================================================================
#
# <++>
#
# by Carlos Vigil Vásquez
# https://github.com/cvigilv/
# ==============================================================================


OPTIONS="<++>"

CHOSEN=$(echo -e "$OPTIONS" | dmenu -i -p "<++>")

case "$CHOSEN" in
    <++>);;
esac
