#!/usr/bin/env python3
#
# =============================================
# <++>.py (version 0.0)
# by Carlos Vigil Vásquez
#
# <++>
#
# https://github.com/cvigilv/
# =============================================

 # SCRIPT HISTORY
_version_="0.0"
_released_="Currently in development"
_title_="<++> - <++> $_version_"

# DEPENDENCIES
# FUNCTIONS
# MAIN
