#!/usr/bin/env python3

# = <++> =======================================================================
#
# <++>
#
# by Carlos Vigil Vásquez
# https://github.com/cvigilv/
# ==============================================================================

__version = '0.0'
__title__ = '<++>.py - <++> (version {})'.format(__version__)

if __name__ == '__main__':
    print(__title__)
